// Generated by CoffeeScript 1.7.1
(function() {
  this.app = require('zappajs')(15000, function() {
    var security, util;
    this.configure((function(_this) {
      return function() {
        _this.use('bodyParser', 'methodOverride', _this.app.router, 'static');
        return _this.set({
          'basepath': '/v1.0'
        });
      };
    })(this));
    this.configure({
      development: (function(_this) {
        return function() {
          return _this.use({
            errorHandler: {
              dumpExceptions: true,
              showStack: true
            }
          });
        };
      })(this),
      production: (function(_this) {
        return function() {
          return _this.use('errorHandler');
        };
      })(this)
    });
    this.enable('serve jquery', 'minify');
    util = require('util');
    security = require('./securitychecker');
    return this.get({
      '/security/status': function() {
        return security.securityCheck((function(_this) {
          return function(res) {
            util.log("GET Security Check result " + res);
            return _this.send(res);
          };
        })(this));
      }
    });
  }).app;

}).call(this);
